# -*- coding: utf-8 -*-
"""projeto1_limpeza.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11bS5lWzZJ9nfVI-2puEUJjvswF1MP2Ba
"""

import pandas as pd
import numpy as np
import matplotlib as plt
#"https://petcc-ufrn.github.io/minicurso-ciencia-de-dados/aulas/projetos/Projeto-dia01.html"

#"importando as bibliotecas"

df1=pd.read_csv('/content/turmas-2023.1.csv', sep=(';'))
df2=pd.read_csv('/content/turmas-2023.2.csv', sep=(';'))
df3=pd.read_csv('/content/turmas-2024-1.csv', sep=(';'))
df4=pd.read_csv('/content/turmas-2024-2.csv', sep=(';'))

#"definindo os df dos arquivos csv's"

#trabalhando na primera tabela 2023.1

display(df1)
df1.info()

#  15180 rows × 26 columns

#observando e corrigindo as duplicatas
display(df1.duplicated().value_counts())

# observase 295 valores True (valores duplicados)

df1.info()

#removendo os valores duplicados
df1.drop_duplicates(inplace=True)
df1.info()
display(df1)

# atualizando os indices
df1.reset_index(drop=True, inplace=True)
display(df1.info())
display(df1)



# Identificando valores ausentes
#soma dos valores nulos em cada coluna
display(df1.isnull().sum())

'''
Remover colunas com muitos valores ausentes

 nas colunas 'matricula_docente_externo', 'observacao', 'id_turma_agrupadora', 'convenio' possuem muitos valores nulos que não
 seram utilizados nas analises, então pode-se exclui-lás
'''
colunas_para_remover = ['matricula_docente_externo', 'observacao', 'id_turma_agrupadora', 'convenio']
df1.drop(columns=colunas_para_remover, inplace=True)

# Verificar o resultado
display(df1.info())
display(df1.isnull().sum())

display(df1.info())
display(df1.isnull().sum())

""" Verificando valores únicos nas colunas com valores ausentes em df1
  Analisando as colunas que ainda possuem "buracos" e quais são seus indices
"""
buracos = ['siape', 'campus_turma', 'local', 'descricao_horario', 'total_solicitacoes', 'capacidade_aluno', 'data_consolidacao', 'qtd_aulas_lancadas']

for col in buracos:
    print(f"Coluna: {col}")
    display(df1[col].value_counts(dropna=False))
    print("-" * 30)

# Tratando valores ausentes em df1

# Para colunas com valores numéricos que podem ser preenchidos com a mediana ou média
# 'total_solicitacoes', 'capacidade_aluno', 'qtd_aulas_lancadas'
df1['total_solicitacoes'].fillna(df1['total_solicitacoes'].median(), inplace=True)
df1['capacidade_aluno'].fillna(df1['capacidade_aluno'].median(), inplace=True)
df1['qtd_aulas_lancadas'].fillna(df1['qtd_aulas_lancadas'].median(), inplace=True)

# Para colunas com valores categóricos que podem ser preenchidos com a moda
# 'campus_turma', 'local', 'descricao_horario', 'situacao_turma', 'modalidade_participantes'
# Note: 'situacao_turma' and 'modalidade_participantes' had no missing values according to .isnull().sum() but are included here for completeness if needed later.
for col in ['campus_turma', 'local', 'descricao_horario']:
    if df1[col].isnull().any():
        most_frequent_value = df1[col].mode()[0]
        df1[col].fillna(most_frequent_value, inplace=True)

# 'siape' e 'data_consolidacao' - estas colunas podem requerer um tratamento mais específico dependendo da análise.
# Por enquanto, vamos preencher 'siape' com 0 (indicando docente externo ou sem informação) e 'data_consolidacao' com um valor placeholder ou deixá-lo como está se não for crucial para a análise.
# Para 'siape', preencher com 0 parece razoável se quisermos manter a linha e indicar a ausência do SIAPE.
df1['siape'].fillna(0, inplace=True)

# Para 'data_consolidacao', se a data for importante, podemos tentar imputar com a data mais frequente ou uma data indicativa de "não consolidado".
# Dado que é uma data/hora, a imputação com a moda pode não ser significativa. Vamos preenchê-la com uma string indicando "Não Consolidado" por enquanto.
df1['data_consolidacao'].fillna('Não Consolidado', inplace=True)


# Verificar se ainda existem valores ausentes
display(df1.isnull().sum())
display(df1.info())

# Tratando valores ausentes restantes em df2

# Para colunas com valores numéricos
df2['total_solicitacoes'] = df2['total_solicitacoes'].fillna(df2['total_solicitacoes'].median())
df2['capacidade_aluno'] = df2['capacidade_aluno'].fillna(df2['capacidade_aluno'].median())
df2['qtd_aulas_lancadas'] = df2['qtd_aulas_lancadas'].fillna(df2['qtd_aulas_lancadas'].median())

# Para colunas com valores categóricos
for col in ['campus_turma', 'local', 'descricao_horario']:
    if df2[col].isnull().any():
        most_frequent_value = df2[col].mode()[0]
        df2[col] = df2[col].fillna(most_frequent_value)

# Coluna 'siape'
df2['siape'] = df2['siape'].fillna(0)

# Coluna 'data_consolidacao'
df2['data_consolidacao'] = df2['data_consolidacao'].fillna('Não Consolidado')

# Verificar se ainda existem valores ausentes em df2
print("\nValores ausentes em df2 após tratamento:")
display(df2.isnull().sum())
display(df2.info())

# Aplicando os passos de limpeza do df1 para o df2

# 1. Verificar e remover duplicatas em df2 e resetar o índice
print("Verificando duplicatas em df2:")
display(df2.duplicated().value_counts())

df2.drop_duplicates(inplace=True)
df2.reset_index(drop=True, inplace=True)
print("\nApós remover duplicatas e resetar o índice em df2:")
display(df2.info())

# 2. Remover colunas com muitos valores ausentes em df2
colunas_para_remover_df2 = ['matricula_docente_externo', 'observacao', 'id_turma_agrupadora', 'convenio']
df2.drop(columns=colunas_para_remover_df2, inplace=True)
print("\nApós remover colunas com muitos valores ausentes em df2:")
display(df2.info())

# 3. Identificando valores ausentes restantes em df2
print("\nValores ausentes restantes em df2:")
display(df2.isnull().sum())

# 4. Tratando valores ausentes restantes em df2

# Para colunas com valores numéricos
df2['total_solicitacoes'] = df2['total_solicitacoes'].fillna(df2['total_solicitacoes'].median())
df2['capacidade_aluno'] = df2['capacidade_aluno'].fillna(df2['capacidade_aluno'].median())
df2['qtd_aulas_lancadas'] = df2['qtd_aulas_lancadas'].fillna(df2['qtd_aulas_lancadas'].median())

# Para colunas com valores categóricos
for col in ['campus_turma', 'local', 'descricao_horario']:
    if df2[col].isnull().any():
        most_frequent_value = df2[col].mode()[0]
        df2[col] = df2[col].fillna(most_frequent_value)

# Coluna 'siape'
df2['siape'] = df2['siape'].fillna(0)

# Coluna 'data_consolidacao'
df2['data_consolidacao'] = df2['data_consolidacao'].fillna('Não Consolidado')

# Verificar se ainda existem valores ausentes em df2 após tratamento
print("\nValores ausentes em df2 após tratamento completo:")
display(df2.isnull().sum())
display(df2.info())

# Aplicando os passos de limpeza para df3

# 1. Verificar e remover duplicatas em df3 e resetar o índice
print("Verificando duplicatas em df3:")
display(df3.duplicated().value_counts())

df3.drop_duplicates(inplace=True)
df3.reset_index(drop=True, inplace=True)
print("\nApós remover duplicatas e resetar o índice em df3:")
display(df3.info())

# 2. Remover colunas com muitos valores ausentes em df3
colunas_para_remover_df3 = ['matricula_docente_externo', 'observacao', 'id_turma_agrupadora', 'convenio']
# Check if columns exist before dropping
cols_to_drop_exist_df3 = [col for col in colunas_para_remover_df3 if col in df3.columns]
if cols_to_drop_exist_df3:
    df3.drop(columns=cols_to_drop_exist_df3, inplace=True)
print("\nApós remover colunas com muitos valores ausentes em df3:")
display(df3.info())

# 3. Identificando valores ausentes restantes em df3
print("\nValores ausentes restantes em df3:")
display(df3.isnull().sum())

# 4. Tratando valores ausentes restantes em df3

# Para colunas com valores numéricos
df3['total_solicitacoes'] = df3['total_solicitacoes'].fillna(df3['total_solicitacoes'].median())
df3['capacidade_aluno'] = df3['capacidade_aluno'].fillna(df3['capacidade_aluno'].median())
df3['qtd_aulas_lancadas'] = df3['qtd_aulas_lancadas'].fillna(df3['qtd_aulas_lancadas'].median())

# Para colunas com valores categóricos
for col in ['campus_turma', 'local', 'descricao_horario']:
    if col in df3.columns and df3[col].isnull().any():
        most_frequent_value = df3[col].mode()[0]
        df3[col] = df3[col].fillna(most_frequent_value)

# Coluna 'siape'
if 'siape' in df3.columns:
    df3['siape'] = df3['siape'].fillna(0)

# Coluna 'data_consolidacao'
if 'data_consolidacao' in df3.columns:
    df3['data_consolidacao'] = df3['data_consolidacao'].fillna('Não Consolidado')

# Verificar se ainda existem valores ausentes em df3 após tratamento
print("\nValores ausentes em df3 após tratamento completo:")
display(df3.isnull().sum())
display(df3.info())

# Aplicando os passos de limpeza para df4

# 1. Verificar e remover duplicatas em df4 e resetar o índice
print("Verificando duplicatas em df4:")
display(df4.duplicated().value_counts())

df4.drop_duplicates(inplace=True)
df4.reset_index(drop=True, inplace=True)
print("\nApós remover duplicatas e resetar o índice em df4:")
display(df4.info())

# 2. Remover colunas com muitos valores ausentes em df4
colunas_para_remover_df4 = ['matricula_docente_externo', 'observacao', 'id_turma_agrupadora', 'convenio']
# Check if columns exist before dropping
cols_to_drop_exist_df4 = [col for col in colunas_para_remover_df4 if col in df4.columns]
if cols_to_drop_exist_df4: # Corrected variable name here
    df4.drop(columns=cols_to_drop_exist_df4, inplace=True)

print("\nApós remover colunas com muitos valores ausentes em df4:")
display(df4.info())

# 3. Identificando valores ausentes restantes em df4
print("\nValores ausentes restantes em df4:")
display(df4.isnull().sum())

# 4. Tratando valores ausentes restantes em df4

# Para colunas com valores numéricos
df4['total_solicitacoes'] = df4['total_solicitacoes'].fillna(df4['total_solicitacoes'].median())
df4['capacidade_aluno'] = df4['capacidade_aluno'].fillna(df4['capacidade_aluno'].median())
df4['qtd_aulas_lancadas'] = df4['qtd_aulas_lancadas'].fillna(df4['qtd_aulas_lancadas'].median())

# Para colunas com valores categóricos
for col in ['campus_turma', 'local', 'descricao_horario']:
    if col in df4.columns and df4[col].isnull().any():
        most_frequent_value = df4[col].mode()[0]
        df4[col] = df4[col].fillna(most_frequent_value)

# Coluna 'siape'
if 'siape' in df4.columns:
    df4['siape'] = df4['siape'].fillna(0)

# Coluna 'data_consolidacao'
if 'data_consolidacao' in df4.columns:
    df4['data_consolidacao'] = df4['data_consolidacao'].fillna('Não Consolidado')

# Verificar se ainda existem valores ausentes em df4 após tratamento
print("\nValores ausentes em df4 após tratamento completo:")
display(df4.isnull().sum())
display(df4.info())

'''
AMOSTRAGEM DOS DADOS FEITOS
'''
# Análise simples do df1 (2023.1)

print("Análise de df1 (2023.1):")
print("\nPrimeiras 5 linhas:")
display(df1.head())

print("\nInformações do DataFrame:")
display(df1.info())

print("\nEstatísticas Descritivas:")
display(df1.describe())

print("\nContagem de valores para 'nivel_ensino':")
display(df1['nivel_ensino'].value_counts())

print("\nContagem de valores para 'situacao_turma':")
display(df1['situacao_turma'].value_counts())

print("\nContagem de valores para 'modalidade_participantes':")
display(df1['modalidade_participantes'].value_counts())

print("-" * 50)

# Análise simples do df2 (2023.2)

print("Análise de df2 (2023.2):")
print("\nPrimeiras 5 linhas:")
display(df2.head())

print("\nInformações do DataFrame:")
display(df2.info())

print("\nEstatísticas Descritivas:")
display(df2.describe())

print("\nContagem de valores para 'nivel_ensino':")
display(df2['nivel_ensino'].value_counts())

print("\nContagem de valores para 'situacao_turma':")
display(df2['situacao_turma'].value_counts())

print("\nContagem de valores para 'modalidade_participantes':")
display(df2['modalidade_participantes'].value_counts())

print("-" * 50)

# Análise simples do df3 (2024.1)

print("Análise de df3 (2024.1):")
print("\nPrimeiras 5 linhas:")
display(df3.head())

print("\nInformações do DataFrame:")
display(df3.info())

print("\nEstatísticas Descritivas:")
display(df3.describe())

print("\nContagem de valores para 'nivel_ensino':")
display(df3['nivel_ensino'].value_counts())

print("\nContagem de valores para 'situacao_turma':")
display(df3['situacao_turma'].value_counts())

print("\nContagem de valores para 'modalidade_participantes':")
display(df3['modalidade_participantes'].value_counts())

print("-" * 50)

# Análise simples do df4 (2024.2)

print("Análise de df4 (2024.2):")
print("\nPrimeiras 5 linhas:")
display(df4.head())

print("\nInformações do DataFrame:")
display(df4.info())

print("\nEstatísticas Descritivas:")
display(df4.describe())

print("\nContagem de valores para 'nivel_ensino':")
display(df4['nivel_ensino'].value_counts())

print("\nContagem de valores para 'situacao_turma':")
display(df4['situacao_turma'].value_counts())

print("\nContagem de valores para 'modalidade_participantes':")
display(df4['modalidade_participantes'].value_counts())

# Unindo os quatro dataframes
df_combined = pd.concat([df1, df2, df3, df4], ignore_index=True)

# Exibir as primeiras linhas e informações do dataframe combinado para verificar o resultado
print("Primeiras 5 linhas do dataframe combinado:")
display(df_combined.head())

print("\nInformações do dataframe combinado:")
display(df_combined.info())

print("\nVerificando valores ausentes no dataframe combinado:")
display(df_combined.isnull().sum())